services:
  backend:
    image: ghcr.io/richardrain/film-react-nest/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: 
      - backend/.env
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: ghcr.io/richardrain/film-react-nest/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - frontend/.env
    volumes:
      - frontend:/app/dist
    networks:
      - internet

  nginx:
    image: ghcr.io/richardrain/film-react-nest/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend:/var/www/frontend:ro
    networks:
      - backend
      - internet
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: 
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    env_file: 
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend
      - internet
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  frontend:
  postgres:
  pgadmin:


networks:
  backend:
    driver: bridge
    internal: true
  internet:
    driver: bridge
