env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: publish
on: [push]
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
        - uses: actions/checkout@v4 # Checking out the repo
        - name: Log in to the Container registry
          uses: docker/login-action@v3.3.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}

        - name: Buildx setup
          uses: docker/setup-buildx-action@v3.8.0

        - name: Build and push Backend Docker image
          uses: docker/build-push-action@v6.13.0
          with:
            context: ./backend
            file: ./backend/Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/RichardRain/film-react-nest/backend:latest
            
        - name: Build and push Frontend Docker image
          uses: docker/build-push-action@v6.13.0
          with:
            context: ./frontend
            file: ./frontend/Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/RichardRain/film-react-nest/frontend:latest

        - name: Build and push Nginx Docker image
          uses: docker/build-push-action@v6.13.0
          with:
            context: ./nginx
            file: ./nginx/Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/RichardRain/film-react-nest/nginx:latest
